### PR TITLE
Fix deadlock when the device doesn't respond right away

### PR DESCRIPTION
**Pull request by not-holar**
Previously, when if the sensor didn't respond right away, the program would get stuck in the while(true) loop

### CODE REVIEW

**Comment by fanfanlatulipe26** [comment]
Thank you for your interest in this small library.

In these examples the purpose of the  

```
  while (true) delay(10);
```

was really to hang : the user get an error message and we stop working.

I admit that your change is interesting, but maybe you could change the delay value in order not to overflow the serial monitor with repeating error messages.

Checking 2 or 3 times per second should be enough. What about delay(500) or some thing the like  ??

If you agree, please make a new pull request and I will manage it.

**Comment by not-holar** [comment]
The reason for this PR is that I've had issues with the example where the sensor would not get initialized right away for whatever reason, but was fine on the second try.
I've increased the loop delay, as per your suggestion, and also added a preliminary one, which should help avoid entering the loop at all (granted that the sensor is connected).

**Comment by fanfanlatulipe26** [comment]
Done

**Comment by fanfanlatulipe26** [comment]
Thank you for the PR !! Best regards
:wink:

**Pull request merged**
