### PR TITLE
Arduino ide can't compile due to unused variable.

### PR DESCRIPTION
**Pull request by diodenschein**
Hello, thanks for making this library.

I noticed Arduino IDE's compiler flags seem to be set to error on unused variables and understandably refuse to compile. 
Would you consider accepting this PR to make it easier for the next one to find these sensors and this library?
Thank you,
Rob

### CODE REVIEW

**Comment by fanfanlatulipe26** [comment]
Thank you for your help.

Just for my information: which release of IDE did you use. ?

Which processor/ core release get problem ?

I ran the tests with IDE 1. 8.19 and I think it was OK.

**Comment by diodenschein** [comment]
Fair point.
I was a bit inaccurate it'll be part of the arduino-esp32 package that causes this. 
Turns out it's a bit older on my current setup:

Arduino Release v2.0.11 based on ESP-IDF v4.4.5
Arduino ide 1.8.19

```
Compiling library "XGZP6897D"
[...]

"C:\\Users\\user\\AppData\\Local\\Arduino15\\packages\\esp32\\tools\\xtensa-esp32s3-elf-gcc\\esp-2021r2-patch5-8.4.0/bin/xtensa-esp32s3-elf-g++" -DHAVE_CONFIG_H "-DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"" -DUNITY_INCLUDE_CONFIG_H -DWITH_POSIX -D_GNU_SOURCE "-DIDF_VER=\"v4.4.5\"" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS "- 

[...]
IC:\\Users\\user\\AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.11/tools/sdk/esp32s3/include/newlib/platform_include" "-
C:\Users\user\Documents\Arduino\libraries\XGZP6897D\src\XGZP6897D.cpp: In member function 'bool XGZP6897D::readRawSensor(int16_t&, int32_t&)':
C:\Users\user\Documents\Arduino\libraries\XGZP6897D\src\XGZP6897D.cpp:42:32: error: unused variable 'deb' [-Werror=unused-variable]
   unsigned long endConversion, deb;
                                ^~~
cc1plus.exe: some warnings being treated as errors
```

**Comment by fanfanlatulipe26** [comment]
OK. I have more or less the same environment.       
I think that I understand why I don't take this error.       
I think that in the IDE preferences   Files/preferences you have "Compiler warnings" set to "more" or "all".           
For ESP32 the developers added -Werror=all when "Compiler warnings" is set to "more" or "all":all warnings are managed as errors ....       
You can see it in the file .....AppData\\Local\\Arduino15\\packages\\esp32\\hardware\\esp32\\2.0.14\\platform.txt  
`# Arduino Compile Warning Levels`  
`compiler.warning_flags=-w`  
`compiler.warning_flags.none=-w`  
`compiler.warning_flags.default=`  
`compiler.warning_flags.more=-Wall -Werror=all`  
`compiler.warning_flags.all=-Wall -Werror=all -Wextra`

             
I use the default setting for  "Compiler warnings" which is "non"e and so didn't get the warning/error.          
         
Anyhow libraries should not make warning and I will merge your pull request and make a new release.             
Thank you ;-)

**Comment by fanfanlatulipe26** [comment]
Done : new release 1.04

**Pull request merged**
